Repository seapath/meta-seapath, pull requests merged in 2022-06, with the labels that each got.

#98 python3-setup-ovs: setup-ovs have now it own repositories
  recipes-votp/python3-setup-ovs/src
  recipes-votp/python3-setup-ovs/src/setup.py
  recipes-votp/python3-setup-ovs/src/setup_open_vswitch/__init__.py
  recipes-votp/python3-setup-ovs/src/setup_open_vswitch/check.py
  recipes-votp/python3-setup-ovs/src/setup_open_vswitch/helpers.py
  recipes-votp/python3-setup-ovs/src/setup_open_vswitch/openflow.py
  recipes-votp/python3-setup-ovs/src/setup_open_vswitch/ovs.py
  recipes-votp/python3-setup-ovs/src/setup_open_vswitch/setup_ovs_exception.py
  recipes-votp/python3-setup-ovs/src/setup_ovs.py
Labels: enhancement

#102 seapath-host-common-virtu: install dpdk-tools
  recipes-core/images/seapath-host-common-virtu.inc
  recipes-extended/dpdk/dpdk_20.%.bbappend
Labels: bug

#101 Support UEFI on flash PXE image
  recipes-core/images/seapath-flash-pxe.bb
  recipes-votp/flash-script/files/flash.sh
Labels: bug, enhancement

#103 python3-setup-ovs: add python3-pyyaml RDEPENDS
  recipes-votp/python3-setup-ovs/python3-setup-ovs.bb
Labels: bug

#106 recipes-core/kbd: bump to version 2.5.0
  recipes-core/kbd/kbd_2.5.0.bb
Labels: bug
