Repository seapath/meta-seapath, pull requests merged in 2023-09, with the labels that each got.

#147 cukinia: add msmtp group in test
  recipes-cukinia-tests/cukinia-tests/files/hypervisor_security_tests.d/groups.conf
Labels: bug, enhancement

#148 wic: reduce efi image size
  wic/mkefidisk.wks.in
Labels: enhancement

#150 classes/security/hardening: Enable CVE extra exclusions
  classes/security/hardening.inc
Labels: enhancement

#149 classes/security/hardening: Enable CVE extra exclusions
  classes/security/hardening.inc
Labels: enhancement

#151 recipes-core/images/seapath-flasher: split into two recipes
  recipes-core/base-files/files/seapath-flash/fstab
  recipes-core/images/seapath-flasher-cpio.bb
  recipes-core/images/seapath-flasher.bb
  wic/flasher.wks.in
Labels: bug

#153 qemu: enable libusb
  recipes-devtools/qemu/qemu_%.bbappend
Labels: enhancement

#152 qemu: enable libusb
  recipes-devtools/qemu/qemu_%.bbappend
Labels: enhancement
