Repository seapath/meta-seapath, pull requests merged in 2024-03, with the labels that each got.

#175 system-config: split security and readonly features
  recipes-core/images/seapath-guest-common.inc
  recipes-core/images/seapath-host-common.inc
  recipes-core/images/seapath-monitor-common.inc
  recipes-votp/system-config/system-config.bb
Labels: enhancement

#180 linuxptp_%.bbappend: removed the '@' from the timemaster.service name
  recipes-connectivity/linuxptp/files/timemaster.service
  recipes-connectivity/linuxptp/linuxptp_%.bbappend
Labels: bug

#184 meta-openembedded: remove linuxptp recipe
  recipes-connectivity/linuxptp/linuxptp/0001-include-string.h-for-strncpy.patch
  recipes-connectivity/linuxptp/linuxptp/0001-makefile-use-conditional-assignment-for-KBUILD_OUTPU.patch
  recipes-connectivity/linuxptp/linuxptp/Use-cross-cpp-in-incdefs.patch
  recipes-connectivity/linuxptp/linuxptp/build-Allow-CC-and-prefix-to-be-overriden.patch
  recipes-connectivity/linuxptp/linuxptp_3.1.1.bb
Labels: enhancement

#183 linux-mainline-rt: enable DRM support as modules
  recipes-kernel/linux/linux-mainline-rt/drm.cfg
  recipes-kernel/linux/linux-mainline-rt_6.1.bb
Labels: bug, enhancement

#185 linux-mainline-rt: bump to 6.1.80-rt26
  recipes-kernel/linux/linux-mainline-rt_6.1.bb
Labels: bug, enhancement
